"""Central configuration for QueueSense AI."""

from __future__ import annotations

from pathlib import Path


# Dataset roots
SHANGHAI_ROOT = "datasets/shanghaitech_with_people_density_map/ShanghaiTech/part_B"
MALL_ROOT = "datasets/mall_dataset"

# GT density maps (generated by scripts/make_density_maps.py)
MALL_DENSITY_DIR = "datasets/mall_dataset/density_maps"

# Model checkpoints
# Primary: mall-tuned model (trained on Mall GT density maps)
# Fallback: original ShanghaiTech-trained model
CHECKPOINT = "runs/mall_tuned/best.pt"
CHECKPOINT_FALLBACK = "runs/density_cnn_tuned/best.pt"

# Outputs
OUTPUT_DIR = "outputs"
ANNOTATED_FRAMES_DIR = "annotated_frames"
HEATMAP_FRAMES_DIR = "heatmap_frames"

# Inference / demo behavior
CROWD_THRESHOLD = 35   # Mall data: mean=31, max=53. Alert above 35.
EVAL_RESIZE = 512      # resize long side before inference

# Gaussian density map generation
DENSITY_SIGMA = 20.0   # Gaussian sigma for head-point density maps (pixels)

def abs_path(path: str | Path) -> Path:
    """Resolve a repo-relative path to an absolute Path."""
    root = Path(__file__).resolve().parent
    return (root / Path(path)).resolve()
