"""Fine-tune SimpleDensityCNN on Mall dataset with GT density maps.

This script takes the ShanghaiTech pre-trained checkpoint and fine-tunes
it on the Mall dataset using the Gaussian density maps generated by
make_density_maps.py. The result is a model that accurately predicts
crowd density in mall-style surveillance scenes.

Usage:
    python scripts/train_mall.py
    python scripts/train_mall.py --epochs 30 --lr 1e-4
"""
from __future__ import annotations

import argparse
import time
from pathlib import Path
import sys

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import cv2
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, random_split
import torchvision.transforms as T
import scipy.io

import config
from crowdcount.model import SimpleDensityCNN
from crowdcount.train_utils import get_device, seed_everything, AverageMeter

IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD = [0.229, 0.224, 0.225]


# ---------------------------------------------------------------------------
# Dataset
# ---------------------------------------------------------------------------

class MallDensityDataset(Dataset):
    """Mall dataset with GT head-position-derived Gaussian density maps."""

    def __init__(
        self,
        mall_root: str | Path,
        density_dir: str | Path,
        resize_long: int = 512,
        augment: bool = False,
        indices: list[int] | None = None,
    ):
        self.root = Path(mall_root)
        self.density_dir = Path(density_dir)
        self.resize_long = resize_long
        self.augment = augment

        self.frame_paths = sorted((self.root / "frames").glob("seq_*.jpg"))
        self.density_paths = sorted(self.density_dir.glob("frame_*.npy"))

        n = min(len(self.frame_paths), len(self.density_paths))
        self.frame_paths = self.frame_paths[:n]
        self.density_paths = self.density_paths[:n]

        if indices is not None:
            self.frame_paths = [self.frame_paths[i] for i in indices]
            self.density_paths = [self.density_paths[i] for i in indices]

        self.transform = T.Compose([
            T.ToTensor(),
            T.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
        ])

    def __len__(self) -> int:
        return len(self.frame_paths)

    def _resize(self, img_bgr: np.ndarray, density: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
        h, w = img_bgr.shape[:2]
        long_side = max(h, w)
        if long_side <= self.resize_long:
            return img_bgr, density
        scale = self.resize_long / float(long_side)
        nw = max(1, int(round(w * scale)))
        nh = max(1, int(round(h * scale)))
        img_resized = cv2.resize(img_bgr, (nw, nh), interpolation=cv2.INTER_LINEAR)
        # Preserve total count when resizing density
        den_resized = cv2.resize(density, (nw, nh), interpolation=cv2.INTER_LINEAR)
        den_resized = den_resized * (float(h * w) / float(nh * nw))
        return img_resized, den_resized.astype(np.float32)

    def __getitem__(self, idx: int) -> dict:
        img_bgr = cv2.imread(str(self.frame_paths[idx]), cv2.IMREAD_COLOR)
        density = np.load(str(self.density_paths[idx])).astype(np.float32)

        img_bgr, density = self._resize(img_bgr, density)

        if self.augment:
            # Random horizontal flip
            if np.random.random() < 0.5:
                img_bgr = cv2.flip(img_bgr, 1)
                density = np.fliplr(density).copy()
            # Random crop (224x224 patch)
            h, w = img_bgr.shape[:2]
            crop = 224
            if h > crop and w > crop:
                y0 = np.random.randint(0, h - crop)
                x0 = np.random.randint(0, w - crop)
                img_bgr = img_bgr[y0:y0+crop, x0:x0+crop]
                density = density[y0:y0+crop, x0:x0+crop]

        img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
        x = self.transform(img_rgb)
        y = torch.from_numpy(density[None, ...]).float()
        gt_count = float(density.sum())

        return {"image": x, "density": y, "gt_count": gt_count}


# ---------------------------------------------------------------------------
# Loss
# ---------------------------------------------------------------------------

class CombinedLoss(nn.Module):
    """MSE on density map + L1 count loss."""

    def __init__(self, count_weight: float = 0.001):
        super().__init__()
        self.mse = nn.MSELoss()
        self.count_weight = count_weight

    def forward(
        self,
        pred_den: torch.Tensor,
        gt_den: torch.Tensor,
        gt_count: torch.Tensor,
    ) -> tuple[torch.Tensor, dict]:
        loss_den = self.mse(pred_den, gt_den)
        pred_count = pred_den.sum(dim=(1, 2, 3))
        loss_count = (pred_count - gt_count).abs().mean()
        loss = loss_den + self.count_weight * loss_count
        return loss, {
            "den": float(loss_den.item()),
            "cnt": float(loss_count.item()),
            "mae": float(loss_count.item()),
        }


# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------

def load_pretrained(ckpt_path: str | Path, device: torch.device) -> SimpleDensityCNN:
    """Load existing checkpoint (any checkpoint) as starting weights."""
    payload = torch.load(str(ckpt_path), map_location="cpu", weights_only=False)
    if isinstance(payload, dict) and "model" in payload:
        ckpt_args = payload.get("args", {})
        base_channels = ckpt_args.get("base_channels", 16)
        model = SimpleDensityCNN(base_channels=base_channels)
        model.load_state_dict(payload["model"], strict=False)
    else:
        model = SimpleDensityCNN()
        model.load_state_dict(payload, strict=False)
    return model.to(device)


@torch.no_grad()
def evaluate(model: nn.Module, loader: DataLoader, device: torch.device) -> tuple[float, float]:
    """Returns (MAE, RMSE) on the given loader."""
    model.eval()
    total_abs = 0.0
    total_sq = 0.0
    n = 0
    for batch in loader:
        x = batch["image"].to(device)
        gt = batch["gt_count"]
        pred = model(x).sum(dim=(1, 2, 3)).cpu()
        err = pred - gt.float()
        total_abs += float(err.abs().sum())
        total_sq += float((err ** 2).sum())
        n += x.size(0)
    mae = total_abs / max(n, 1)
    rmse = (total_sq / max(n, 1)) ** 0.5
    return mae, rmse


def main() -> None:
    ap = argparse.ArgumentParser(description="Fine-tune CNN on Mall GT density maps.")
    ap.add_argument("--mall-root", type=str, default="datasets/mall_dataset")
    ap.add_argument("--density-dir", type=str, default="datasets/mall_dataset/density_maps")
    ap.add_argument("--pretrain", type=str, default=config.CHECKPOINT_FALLBACK,
                    help="Starting checkpoint path")
    ap.add_argument("--out-dir", type=str, default="runs/mall_tuned")
    ap.add_argument("--epochs", type=int, default=40)
    ap.add_argument("--lr", type=float, default=5e-4)
    ap.add_argument("--batch-size", type=int, default=4)
    ap.add_argument("--val-split", type=float, default=0.15,
                    help="Fraction of frames held out for validation")
    ap.add_argument("--resize", type=int, default=512)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--device", type=str, default="auto")
    args = ap.parse_args()

    seed_everything(args.seed)
    device = get_device(args.device)
    print(f"Device: {device}")

    out_dir = PROJECT_ROOT / args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    # Build train/val split indices
    density_paths = sorted((PROJECT_ROOT / args.density_dir).glob("frame_*.npy"))
    n_total = len(density_paths)
    if n_total == 0:
        raise FileNotFoundError(f"No density maps found in {args.density_dir}. "
                                "Run scripts/make_density_maps.py first.")

    n_val = max(1, int(round(n_total * args.val_split)))
    n_train = n_total - n_val
    rng = np.random.default_rng(args.seed)
    all_idx = rng.permutation(n_total).tolist()
    train_idx = all_idx[:n_train]
    val_idx = all_idx[n_train:]

    train_ds = MallDensityDataset(
        args.mall_root, args.density_dir,
        resize_long=args.resize, augment=True, indices=train_idx,
    )
    val_ds = MallDensityDataset(
        args.mall_root, args.density_dir,
        resize_long=args.resize, augment=False, indices=val_idx,
    )
    train_loader = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True,
                              num_workers=0, pin_memory=False)
    val_loader = DataLoader(val_ds, batch_size=1, shuffle=False, num_workers=0)

    print(f"Train: {len(train_ds)} frames | Val: {len(val_ds)} frames")

    # Load pretrained model
    pretrain_path = config.abs_path(args.pretrain)
    print(f"Loading pretrained weights from {pretrain_path}")
    model = load_pretrained(pretrain_path, device)

    criterion = CombinedLoss(count_weight=0.001)
    optimizer = optim.Adam(model.parameters(), lr=args.lr, weight_decay=1e-5)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=args.epochs, eta_min=1e-6)

    best_mae = float("inf")
    best_epoch = 0

    print(f"\nTraining for {args.epochs} epochs...")
    print("-" * 65)

    for epoch in range(1, args.epochs + 1):
        model.train()
        meter_loss = AverageMeter()
        meter_mae = AverageMeter()
        t0 = time.time()

        for batch in train_loader:
            x = batch["image"].to(device)
            gt_den = batch["density"].to(device)
            gt_count = batch["gt_count"].to(device).float()

            optimizer.zero_grad()
            pred_den = model(x)

            # Resize pred to match gt if needed
            if pred_den.shape != gt_den.shape:
                pred_den = torch.nn.functional.interpolate(
                    pred_den, size=gt_den.shape[2:], mode="bilinear", align_corners=False
                )

            loss, info = criterion(pred_den, gt_den, gt_count)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=5.0)
            optimizer.step()

            meter_loss.update(float(loss.item()), n=x.size(0))
            meter_mae.update(info["mae"], n=x.size(0))

        scheduler.step()
        val_mae, val_rmse = evaluate(model, val_loader, device)
        elapsed = time.time() - t0

        is_best = val_mae < best_mae
        if is_best:
            best_mae = val_mae
            best_epoch = epoch
            torch.save(
                {"model": model.state_dict(), "epoch": epoch, "mae": val_mae,
                 "args": {"base_channels": 16}},
                out_dir / "best.pt",
            )

        print(
            f"Epoch {epoch:3d}/{args.epochs} | "
            f"loss={meter_loss.avg:.4f} | "
            f"train_mae={meter_mae.avg:.2f} | "
            f"val_mae={val_mae:.2f} | "
            f"val_rmse={val_rmse:.2f} | "
            f"lr={scheduler.get_last_lr()[0]:.2e} | "
            f"{elapsed:.1f}s"
            + (" [BEST]" if is_best else "")
        )

    # Save last checkpoint
    torch.save(
        {"model": model.state_dict(), "epoch": args.epochs, "args": {"base_channels": 16}},
        out_dir / "last.pt",
    )

    print(f"\nBest val MAE: {best_mae:.2f} at epoch {best_epoch}")
    print(f"Saved best model to: {out_dir / 'best.pt'}")


if __name__ == "__main__":
    main()
